name: CI Build
on: [push, pull_request]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: "zulu"
        java-version: 8
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
#    - uses: codecov/codecov-action@v1
#      with:
#        file: ./build/reports/jacoco/test/jacocoTestReport.xml
#        fail_ci_if_error: true
